apiVersion: v1
kind: Service
metadata:
  labels:
    app: lookup
  name: restapi-lookup-service
spec:
  ports:
    - nodePort: 31727
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: lookup
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}